import csv
import imaplib
import os
import smtplib
from datetime import datetime
from email.message import EmailMessage
from email.parser import BytesParser
from email.policy import default
from pathlib import Path


BASE_DIR = Path(__file__).parent
DATA_DIR = BASE_DIR / "data"
OUTPUT_DIR = BASE_DIR / "output"

FLIGHT_FILE = DATA_DIR / "flight_status.csv"
EMAIL_PREVIEW_FILE = OUTPUT_DIR / "flight_status_email_preview.txt"


def load_env_file(env_path: Path) -> None:
    """
    Load local environment variables from a .env file.

    This keeps secrets like app passwords out of the Python code.
    """

    if not env_path.exists():
        return

    with env_path.open("r") as file:
        for line in file:
            line = line.strip()

            if not line or line.startswith("#") or "=" not in line:
                continue

            key, value = line.split("=", 1)
            os.environ.setdefault(key, value)


def read_flight_data(file_path: Path) -> list[dict]:
    """
    Read flight status data from a CSV file.
    """

    with file_path.open("r", newline="") as file:
        reader = csv.DictReader(file)
        return list(reader)


def filter_flight_alerts(flights: list[dict]) -> list[dict]:
    """
    Keep flights that need attention.

    For this demo, delayed and cancelled flights are included in the alert.
    """

    alert_statuses = {"Delayed", "Cancelled"}

    return [
        flight
        for flight in flights
        if flight["status"] in alert_statuses
    ]


def build_email_body(alert_flights: list[dict]) -> str:
    """
    Build a plain-text flight operations email summary.
    """

    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    lines = [
        "Flight Operations Status Summary",
        "================================",
        f"Generated at: {timestamp}",
        "",
        "Flights Requiring Attention:",
        "",
    ]

    if not alert_flights:
        lines.append("No delayed or cancelled flights found.")
    else:
        for flight in alert_flights:
            lines.append(
                f"- Flight {flight['flight_number']} "
                f"{flight['origin']} to {flight['destination']} | "
                f"Status: {flight['status']} | "
                f"Delay: {flight['delay_minutes']} minutes | "
                f"Gate: {flight['gate']}"
            )

    lines.extend(
        [
            "",
            "Note: This is a demo email generated by a Python automation project.",
        ]
    )

    return "\n".join(lines)


def save_email_preview(subject: str, body: str) -> None:
    """
    Save a local preview of the email for review and screenshots.
    """

    OUTPUT_DIR.mkdir(exist_ok=True)

    with EMAIL_PREVIEW_FILE.open("w") as file:
        file.write(f"Subject: {subject}\n")
        file.write("\n")
        file.write(body)

    print(f"Email preview saved: {EMAIL_PREVIEW_FILE}")


def send_email(subject: str, body: str) -> None:
    """
    Send the email using Gmail SMTP and an app password.
    """

    sender = os.environ.get("EMAIL_SENDER")
    app_password = os.environ.get("EMAIL_APP_PASSWORD")
    recipient = os.environ.get("EMAIL_RECIPIENT")

    if not sender or not app_password or not recipient:
        raise ValueError(
            "Missing email configuration. Check EMAIL_SENDER, "
            "EMAIL_APP_PASSWORD, and EMAIL_RECIPIENT in your .env file."
        )

    message = EmailMessage()
    message["Subject"] = subject
    message["From"] = sender
    message["To"] = recipient
    message.set_content(body)

    with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
        server.login(sender, app_password)
        server.send_message(message)

    print(f"Email sent to: {recipient}")


def check_inbox_for_subject(subject: str) -> None:
    """
    Optional IMAP check.

    This searches the inbox for the email subject and prints a simple confirmation.
    """

    sender = os.environ.get("EMAIL_SENDER")
    app_password = os.environ.get("EMAIL_APP_PASSWORD")

    if not sender or not app_password:
        raise ValueError(
            "Missing EMAIL_SENDER or EMAIL_APP_PASSWORD for inbox check."
        )

    with imaplib.IMAP4_SSL("imap.gmail.com") as mail:
        mail.login(sender, app_password)
        mail.select("inbox")

        search_query = f'(SUBJECT "{subject}")'
        result, data = mail.search(None, search_query)

        if result != "OK" or not data[0]:
            print("Inbox check completed: no matching email found.")
            return

        email_ids = data[0].split()
        latest_email_id = email_ids[-1]

        result, message_data = mail.fetch(latest_email_id, "(RFC822)")

        if result != "OK":
            print("Inbox check completed: matching email found, but fetch failed.")
            return

        message = BytesParser(policy=default).parsebytes(message_data[0][1])

        print("Inbox check completed: matching email found.")
        print(f"Retrieved subject: {message['Subject']}")
        print(f"Retrieved from: {message['From']}")


def main() -> None:
    """
    Main workflow for the flight status email automation demo.
    """

    load_env_file(BASE_DIR / ".env")

    flights = read_flight_data(FLIGHT_FILE)
    alert_flights = filter_flight_alerts(flights)

    subject = "Flight Operations Status Summary"
    body = build_email_body(alert_flights)

    save_email_preview(subject, body)

    send_email_enabled = os.environ.get("SEND_EMAIL", "false").lower() == "true"
    check_inbox_enabled = os.environ.get("CHECK_INBOX", "false").lower() == "true"

    if send_email_enabled:
        send_email(subject, body)

        if check_inbox_enabled:
            check_inbox_for_subject(subject)
    else:
        print("SEND_EMAIL is false. Preview created, but no email was sent.")


if __name__ == "__main__":
    main()
